Almost eliminated use of /tmp files, added cleanup for the 2 remaining ones in pre-commit.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -59,6 +59,7 @@ init() {
     echo "pre-commit: '.git' directory not found; not being run from a git repo?"
     exit 1
   fi
+
   REPO_ROOT=$(pwd)
   HOOK_DIR=$(pwd)/.git/hooks
   STAGED_FILES=/tmp/git-staged.$$
@@ -74,6 +75,9 @@ init() {
     # (This is a special value, not random. It's the SHA of the empty-tree).
     AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
   fi
+
+  # If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline
+  set -o pipefail
 }
 
 # Check that we're not committing directly into the default branch by mistake.
@@ -95,9 +99,10 @@ check_branch() {
 get_staged_files() {
   # Use --name-status rather than --name-only so we can omit renamed and deleted files.
   # Redirect to a tmp file rather than store the output in a variable. This way we can handle filenames with spaces.
-  git diff --cached --name-status ${AGAINST} > /tmp/git.out.$$
-  grep -v '^D' < /tmp/git.out.$$ | sed -e 's/^.*\t//' > "$STAGED_FILES"
-  grep '^R' < /tmp/git.out.$$ | sed -e "s/^R[0-9a-f]*\t//; s/\t/:::/" > "$RENAMED_FILES"
+  grep -v '^D' <(git diff --cached --name-status ${AGAINST}) | sed -e 's/^.*\t//' > "$STAGED_FILES"
+  grep '^R'    <(git diff --cached --name-status ${AGAINST}) | sed -e "s/^R[0-9a-f]*\t//; s/\t/:::/" > "$RENAMED_FILES"
+
+  trap 'cleanup' EXIT INT TERM
 }
 
 # Check for "n o c o m m i t" comments (I am trying to avoid having the actual word in this script, so that
@@ -196,18 +201,19 @@ check_for_secrets() {
 }
 
 check_diffs_for_secrets() {
-  local file="$*"
-  grep -v "^-" \
+  local file="$*" grep_output
+
+  if grep_output=$(grep -v "^-" \
     | grep -iv "\(supersecret\)\|\(ENC(\)\|\(app.encryption.password\)\|\(secretRef:\)" \
-    | grep -i "\(secret.*[:=]\)\|\(privatekey.*[:=]\)\|\(password.*[:=]\)" > /tmp/grep.$$.out \
-    && {
-      grep -i "^$file\$" "$HOOK_DIR/.secretsok" > /dev/null 2>&1 || {
-        echo -e "! ❌ $file appears to contain secrets:\n $(sed -e 's/^/    /' < /tmp/grep.$$.out)"
-        echo -e "!   To disable checking this file for secrets:"
-        echo -e "!   echo $file >> .git/hooks/.secretsok\\\\n"
-      }
-      rm /tmp/grep.$$.out
-    }
+    | grep -i "\(secret.*[:=]\)\|\(privatekey.*[:=]\)\|\(password.*[:=]\)")
+  then
+    if ! grep -i "^$file\$" "$HOOK_DIR/.secretsok" > /dev/null 2>&1; then
+      # shellcheck disable=SC2001
+      echo -e "! ❌ $file appears to contain secrets:\n $(echo "$grep_output" | sed -e 's/^/    /')"
+      echo -e "!    To disable checking this file for secrets:"
+      echo -e "!    echo $file >> .git/hooks/.secretsok\\\\n"
+    fi
+  fi
 }
 
 run_extra_hooks() {
@@ -237,6 +243,11 @@ go_no_go() {
   fi
 
   echo "pre-commit: ✅ All tests pass!"
+}
+
+cleanup() {
+  rm "$STAGED_FILES" >& /dev/null
+  rm "$RENAMED_FILES" >& /dev/null
 }
 
 main
diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -16,7 +16,7 @@ main() {
   echo "In pre-push($remote, $url)"
   init
 
-  examine_commits
+  #examine_commits
   ensure_cargo_version_is_updated
   cargo_fmt_check
 
@@ -52,8 +52,12 @@ init() {
     exit 1
   fi
 
+  # shellcheck disable=SC2034
   REPO_ROOT=$(pwd)
   HOOK_DIR=$(pwd)/.git/hooks
+
+  # If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline
+  set -o pipefail
 }
 
 # We're not doing anything with individual commits yet, but leaving this function here for future use.
@@ -99,7 +103,7 @@ ensure_cargo_version_is_updated() {
   [[ -e "$HOOK_DIR/.no_version_check" ]] && return
 
   # Check if lock file is tracked.
-  local lock_file
+  local lock_file rev_list
   git ls-files --error-unmatch Cargo.lock >& /dev/null && lock_file="Cargo.lock "
 
   echo "pre-push: Checking that version has been updated in Cargo.toml..."
@@ -109,16 +113,16 @@ ensure_cargo_version_is_updated() {
   # Get the list of revisions being pushed.
   # Helpful link:
   # https://stackoverflow.com/questions/78121361/how-to-get-the-list-of-files-that-will-be-pushed-in-git-push
-  git rev-list HEAD --not --remotes > /tmp/git-rev-list.out
+  rev_list=$(git rev-list HEAD --not --remotes)
 
   # No revisions being pushed? (Happens if you inadvertently run git push twice in a row)
-  if [[ ! -s /tmp/git-rev-list.out ]]; then
+  if [[ -z "$rev_list" ]]; then
     echo "Nothing being pushed; remote is up-to-date."
     return 0
   fi
 
-  oldest_rev=$(tail -n 1 /tmp/git-rev-list.out)
-  newest_rev=$(head -n 1 /tmp/git-rev-list.out)
+  oldest_rev=$(echo -e "$rev_list" | tail -n 1)
+  newest_rev=$(echo -e "$rev_list" | head -n 1)
   default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
   branch="$(git rev-parse --abbrev-ref HEAD)"
 
